"""Issue #120 acceptance lock for the Opportunity Matrix ("CAD Lore").

The unit tests cover individual helpers. This file pins the story contract:
model x CAD x plugin axes, optional domain/process axis support, weighted scoring,
plugin-vacancy detection, and generated JSON/HTML/report surfaces.
"""

from __future__ import annotations

import json
from pathlib import Path

from makerbench import opportunity_matrix as om

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "OPPORTUNITY_MATRIX.md"
REPORT = ROOT / "docs" / "OPPORTUNITY_VACANCIES.md"
SITE_JSON = ROOT / "site" / "data" / "opportunity-matrix.json"
SITE_HTML = ROOT / "site" / "opportunity-matrix.html"
GENERATOR = ROOT / "scripts" / "generate_opportunity_matrix.py"

REQUIRED_WEIGHTS = {
    "capability": 0.40,
    "autonomy": 0.25,
    "openness": 0.20,
    "ease": 0.15,
}


def test_story_120_axes_and_weights_match_cad_lore_brief():
    cube = om.build_cube()

    assert cube["schema"] == "makerbench-opportunity-matrix-v1"
    assert cube["weights"] == REQUIRED_WEIGHTS
    assert abs(sum(cube["weights"].values()) - 1.0) < 1e-9
    assert {model["id"] for model in cube["axes"]["model"]}.issuperset(
        {"claude-opus", "gpt-5", "gemini-3"}
    )
    assert {cad["id"] for cad in cube["axes"]["cad"]}.issuperset(
        {"openscad", "cadquery", "blender", "fusion360", "solidworks"}
    )
    assert {plugin["id"] for plugin in cube["axes"]["plugin"]}.issuperset(
        {"none", "python-sdk", "blender-mcp", "adam", "leo-aura"}
    )


def test_story_120_optional_fourth_axes_are_supported_but_separate():
    domain_cube = om.build_cube(with_domain=True)
    process_cube = om.build_cube(with_process=True)

    assert domain_cube["axes"]["domain"]
    assert all(coord["domain"] is not None for coord in domain_cube["coordinates"])
    assert all(coord.get("process") is None for coord in domain_cube["coordinates"])

    assert process_cube["axes"]["process"]
    assert all(coord["process"] is not None for coord in process_cube["coordinates"])
    assert not process_cube["axes"]["domain"]
    assert all(coord["domain"] is not None for coord in process_cube["coordinates"])


def test_story_120_vacancy_rule_ranks_empty_high_potential_coordinates():
    cube = om.build_cube()
    vacancies = cube["top_vacancies"]

    assert cube["counts"]["vacancies"] > 0
    assert vacancies
    assert all(v["is_vacancy"] for v in vacancies)
    assert all(not v["has_evidence"] for v in vacancies)
    assert all(v["opportunity_score"] is None for v in vacancies)
    assert [v["potential_score"] for v in vacancies] == sorted(
        (v["potential_score"] for v in vacancies),
        reverse=True,
    )


def test_story_120_plugin_compatibility_prunes_impossible_cells():
    cube = om.build_cube()
    coords = cube["coordinates"]

    assert not [
        coord for coord in coords
        if coord["plugin"] == "blender-mcp" and coord["cad"] != "blender"
    ]
    assert not [
        coord for coord in coords
        if coord["plugin"] == "solidworks-api" and coord["cad"] != "solidworks"
    ]
    assert {coord["cad"] for coord in coords if coord["plugin"] == "none"} == {
        cad["id"] for cad in cube["axes"]["cad"]
    }


def test_story_120_committed_outputs_are_generator_facing_surfaces():
    site_payload = json.loads(SITE_JSON.read_text(encoding="utf-8"))
    html = SITE_HTML.read_text(encoding="utf-8")
    report = REPORT.read_text(encoding="utf-8")

    assert site_payload["schema"] == om.SCHEMA
    assert site_payload["counts"]["coordinates"] == len(site_payload["coordinates"])
    assert site_payload["top_vacancies"]
    assert "Opportunity Matrix" in html
    assert "Top Vacancies" in html
    assert "plugin vacancies" in html
    assert "Generated by `scripts/generate_opportunity_matrix.py`" in report


def test_story_120_docs_and_generator_name_the_decision_engine_contract():
    doc = DOC.read_text(encoding="utf-8")
    generator = GENERATOR.read_text(encoding="utf-8")

    for needle in (
        "LLM Model × CAD(×plugin) × Art/Field/Expertise",
        "WorkflowManifest",
        "HumanInterventionIndex",
        "score = 0.40·capability + 0.25·autonomy + 0.20·openness + 0.15·ease",
        "plugin vacancy",
        "decision engine",
        "Top Vacancies",
    ):
        assert needle in doc

    for needle in (
        "opportunity-matrix.json",
        "opportunity-matrix.html",
        "OPPORTUNITY_VACANCIES.md",
        "proven cells solid",
        "plugin vacancies",
    ):
        assert needle in generator
