#!/usr/bin/env bash
# Files the MakerBench pre-public backlog as GitHub issues.
# Requires an authenticated GitHub CLI (`gh auth login`) with repo access.
# Run from the repo root:  bash scripts/file_backlog_issues.sh
set -euo pipefail

REPO="tonykoop/makerbench-hwe"
gh issue create --repo "$REPO" \
  --title "Pin grading dependencies / add a lockfile for score reproducibility" \
  --body "All runtime deps in \`pyproject.toml\` are \`>=\` floors. For a benchmark whose value is deterministic grading, a transitive change in \`trimesh\`/\`manifold3d\`/\`shapely\` can silently shift scores and break cross-run comparability.

**Proposal**
- Pin the grading-critical deps to exact versions (at minimum \`trimesh\`, \`manifold3d\`, \`shapely\`, \`rtree\`, \`numpy\`, \`scipy\`), or ship a lockfile (\`uv.lock\`/\`requirements.lock\`) and install from it in CI and on \`makerbench regrade-results\`.
- Record the resolved grading-toolchain versions in \`grader_environment\` (already a field) and consider failing regrade when they diverge from the recorded set.

Suggested labels: enhancement, reproducibility"

gh issue create --repo "$REPO" \
  --title "Fix shapely 'resolution' DeprecationWarning (use quad_segs)" \
  --body "The synthetic-oracle / 2D grading path triggers: \`DeprecationWarning: The 'resolution' argument is deprecated. Use 'quad_segs' instead\` (shapely buffer/geometry calls). Surfaces ~10x in \`tests/test_synthetic_oracle.py\`.

**Fix**: replace \`resolution=\` with \`quad_segs=\` in the shapely calls. Optionally add a \`filterwarnings = error\` for this category in pytest config so future deprecations fail loudly.

Suggested labels: bug, good first issue"

gh issue create --repo "$REPO" \
  --title "Document provenance of site/assets/meshes/*.stl (derived from submissions, not oracles)" \
  --body "\`site/assets/meshes/*.stl\` are committed and named after task families (e.g. \`enclosure_fastened.stl\`). They are generated by \`makerbench/viewer_export.py\` from **submitted** artifacts, not oracle geometry — but an external reviewer cannot verify that from the file alone, and the naming makes them look like leaked task geometry.

**Proposal**
- Add a short \`site/assets/meshes/README.md\` stating they are pipeline-generated from submitted artifacts, never oracle geometry, and how to regenerate.
- Optionally include the source result/artifact id in a sidecar so provenance is checkable.

Suggested labels: documentation, integrity"

gh issue create --repo "$REPO" \
  --title "Add CODE_OF_CONDUCT.md and a contribution license signal (DCO or CLA)" \
  --body "Pre-public governance gaps for a community-submission benchmark:
- No \`CODE_OF_CONDUCT.md\` (Contributor Covenant is the usual choice).
- \`CONTRIBUTING.md\` has no contribution license signal. Decide between a DCO \`Signed-off-by\` (lightweight, enforce via a DCO check) or a CLA, document it, and reflect it in the PR template checklist.

Suggested labels: documentation, governance"

gh issue create --repo "$REPO" \
  --title "Pre-public checklist: confirm oracles repo is private and deploy key is read-only" \
  --body "Before flipping this repo public, confirm the private side once more:
- [ ] \`makerbench-oracles\` (the \`private/oracles\` submodule target) is a **private** repo.
- [ ] \`ORACLES_DEPLOY_KEY\` is a **read-only** deploy key scoped to that repo only.
- [ ] Fork PRs cannot access the secret (already true — secrets aren't shared with fork PRs; selftest is gated on key presence).
- [ ] No oracle source or private seed is reachable through this repo's git history (audited clean as of this writing).
- [ ] The Python 3.10 \`datetime.UTC\` import bug is fixed and the 3.10–3.12 CI matrix is green, so the first public contributor CI run doesn't fail.

Suggested labels: integrity, release"

gh issue create --repo "$REPO" \
  --title "Leaderboard: add a cost-normalized axis (score per dollar / per token)" \
  --body "Telemetry already records token usage and cost (\`usage\`/\`cost\`, see docs/USAGE_TELEMETRY.md). Expose a cost-normalized view on the leaderboard — score-per-dollar (or per-1M-tokens) — as a sortable column/axis.

**Why**: a differentiating headline, and it resists the 'just spend more tokens' critique by rewarding efficient self-verification. Note the subscription-CLI channels record cost as an estimate, not a bill (#6) — display those distinctly.

Suggested labels: enhancement, site"

gh issue create --repo "$REPO" \
  --title "Leaderboard: surface statistical spread (per-cell N and confidence intervals)" \
  --body "docs/SEED_POLICY.md already tracks per-cell N and score spread, but the board presents single win-rates. Show the uncertainty: per-cell N and a confidence interval (or min–max band) per model/task cell, so close rankings aren't over-interpreted.

**Proposal**: extend \`site/build_data.py\` to emit N and CI into \`leaderboard.json\`, and render error bars / an N badge in \`site/index.html\`.

Suggested labels: enhancement, methodology, site"

gh issue create --repo "$REPO" \
  --title "Add a human / expert-machinist baseline to calibrate the four failure levels" \
  --body "There is a deterministic baseline agent (control) but no human reference. A small set of human (ideally expert machinist / mechanical designer) runs on the public dev seeds would calibrate where Levels 1–4 (structural → geometric → physics → DFM) actually sit and give the leaderboard a meaningful 'human line'.

**Scope**: pick a handful of representative tasks, collect a few human solutions, grade them with the public grader, and add a \`human-baseline\` profile.

Suggested labels: enhancement, methodology"

gh issue create --repo "$REPO" \
  --title "Add a one-command 'reproduce a single public result' smoke for newcomers" \
  --body "Newcomers without oracle access can't run \`selftest\` (needs the private submodule). Provide a single command that regrades one committed public result bundle end-to-end (compile → grade → compare to recorded scalars) so anyone can verify the harness works and trust the pipeline.

**Proposal**: e.g. \`makerbench regrade-results --demo\` (or a \`scripts/repro_one.sh\`) that picks a committed \`results/.../r_*.json\`, regrades its source artifact, and prints a pass/fail diff. Document it in the README Quickstart.

Suggested labels: enhancement, docs, onboarding"

echo "All backlog issues filed."
