#!/usr/bin/env python3
"""generate_best_combo_per_craft.py — best (model × CAD × plugin) combo per craft (#183).

Specializes the Opportunity Matrix (#120) to the fabrication-process / craft axis
and emits two surfaces:

  * site/data/best-combo-per-craft.json — the per-craft report
    (schema makerbench-best-combo-per-craft-v1), consumed by the front-page
    Opportunity Matrix surface (#120 / #121).
  * docs/BEST_COMBO_PER_CRAFT.md — the human-readable report: per craft, the
    winning combo (or "vacant" when no manifest evidence exists yet) and the
    ranked high-value vacancies (the per-craft build backlog).

Demonstrated capability is read from results/ (RunResults); WorkflowManifest
evidence — attributed to a craft via the instrument corpus manifest (see
docs/INSTRUMENT_WORKFLOW_CORPUS.md) — promotes a coordinate from "vacancy" to
"proven" for that craft. The core is stdlib-only, so the report regenerates
anywhere.

Usage:
    python3 scripts/generate_best_combo_per_craft.py \
        [--results-dir results] [--runs-root results] [--top-n 10] \
        [--output-json site/data/best-combo-per-craft.json] \
        [--output-report docs/BEST_COMBO_PER_CRAFT.md]
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]


def _load(mod_name: str, rel_path: str):
    spec = importlib.util.spec_from_file_location(mod_name, _ROOT / rel_path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# Load opportunity_matrix first so best_combo_per_craft's ``from . import`` resolves
# without requiring the full package to be importable (mirrors the sibling script).
_om = _load("makerbench.opportunity_matrix", "makerbench/opportunity_matrix.py")
try:  # normal path: real package import
    from makerbench import best_combo_per_craft as _bc  # type: ignore
except Exception:  # pragma: no cover - bare-Python fallback
    import types

    pkg = sys.modules.setdefault("makerbench", types.ModuleType("makerbench"))
    pkg.opportunity_matrix = _om  # type: ignore[attr-defined]
    sys.modules["makerbench.opportunity_matrix"] = _om
    _bc = _load("makerbench.best_combo_per_craft", "makerbench/best_combo_per_craft.py")


def _winner_cell(craft: dict) -> str:
    winner = craft["winner"]
    if not winner:
        return "_vacant — no manifest evidence yet_"
    return (
        f"**{_bc.coordinate_label(winner)}** "
        f"(opportunity {winner['opportunity_score']:.3f}, "
        f"{winner['n_runs']} run{'s' if winner['n_runs'] != 1 else ''})"
    )


def render_report(report: dict, limit: int = 5) -> str:
    counts = report["counts"]
    weights = " · ".join(f"{k} {v}" for k, v in report["weights"].items())
    lines = [
        "# Best combo per craft — the Opportunity Matrix narrowed to a process",
        "",
        "> Generated by `scripts/generate_best_combo_per_craft.py` from the scored",
        "> model × CAD × plugin cube, partitioned by fabrication process. Do not edit",
        "> by hand — see [`OPPORTUNITY_MATRIX.md`](OPPORTUNITY_MATRIX.md) for the",
        "> scoring spec and [`INSTRUMENT_WORKFLOW_CORPUS.md`](INSTRUMENT_WORKFLOW_CORPUS.md)",
        "> for the craft/process vocabulary and instrument corpus manifest (#183).",
        "",
        f"- Crafts (process axis): **{counts['processes']}**",
        f"- Instrument corpus entries: **{counts['corpus_instruments']}**",
        f"- Crafts with workflow-track evidence: **{counts['crafts_with_evidence']}**",
        f"- Proven coordinates (across crafts): **{counts['proven']}**",
        "",
        f"Scoring weights: `{weights}`. Potential is the model capability prior ×",
        "openness × ease × autonomy affinity, weighted and scaled by the craft's",
        "MakerBench-domain demand; opportunity replaces the prior with demonstrated",
        "capability/autonomy once a craft has WorkflowManifest evidence.",
        "",
        "## Winning combo per craft",
        "",
        "| Craft | MakerBench domain | Winning combo | High-value vacancy (top of backlog) |",
        "| ----- | ----------------- | ------------- | ----------------------------------- |",
    ]
    for craft in report["crafts"]:
        top_vac = craft["top_vacancies"][0] if craft["top_vacancies"] else None
        vac_cell = (
            f"{_bc.coordinate_label(top_vac)} ({top_vac['potential_score']:.3f})"
            if top_vac else "—"
        )
        lines.append(
            f"| {craft['label']} | {craft['domain']} | {_winner_cell(craft)} | {vac_cell} |"
        )

    lines += [
        "",
        "## Per-craft detail",
        "",
        "Each craft pulls real briefs from the instrument library entries listed under",
        "it. The vacancy list is that craft's ranked build backlog — the highest-leverage",
        "empty (model × CAD × plugin) coordinates to stand up next.",
        "",
    ]
    corpus_by_process: dict[str, list[str]] = {}
    for entry in report["corpus"]:
        for pid in entry["processes"]:
            corpus_by_process.setdefault(pid, []).append(entry["repo"])

    for craft in report["crafts"]:
        instruments = ", ".join(corpus_by_process.get(craft["process"], [])) or "—"
        lines += [
            f"### {craft['label']}  ·  `{craft['process']}`",
            "",
            f"{craft['blurb']}",
            "",
            f"- MakerBench domain: **{craft['domain']}**"
            f"{' (live grader)' if craft['live'] else ' (scaffolded)'}",
            f"- Corpus instruments: {instruments}",
            f"- Winning combo: {_winner_cell(craft)}",
            "",
        ]
        if craft["top_proven"]:
            lines += [
                "| # | Model × CAD × Plugin | Opportunity | Capability | Autonomy | Runs |",
                "| - | -------------------- | ----------: | ---------: | -------: | ---: |",
            ]
            for rank, p in enumerate(craft["top_proven"][:limit], start=1):
                lines.append(
                    f"| {rank} | {_bc.coordinate_label(p)} | {p['opportunity_score']:.3f} | "
                    f"{p['capability']} | {p['autonomy']} | {p['n_runs']} |"
                )
            lines.append("")
        lines += [
            "High-value vacancies (ranked by potential):",
            "",
            "| # | Model × CAD × Plugin | Potential | Openness | Ease |",
            "| - | -------------------- | --------: | -------: | ---: |",
        ]
        for rank, v in enumerate(craft["top_vacancies"][:limit], start=1):
            lines.append(
                f"| {rank} | {_bc.coordinate_label(v)} | {v['potential_score']:.3f} | "
                f"{v['openness']} | {v['ease']} |"
            )
        lines.append("")

    if not counts["crafts_with_evidence"]:
        lines += [
            "> _No WorkflowManifest evidence has been attributed to any craft yet —"
            " every craft is currently all-vacancy (pure potential). As the workflow"
            " track (#100) lands manifests against real instrument briefs, winning"
            " combos will surface per craft._",
            "",
        ]
    return "\n".join(lines)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Generate the best-combo-per-craft report (#183)")
    p.add_argument("--results-dir", type=Path, default=_ROOT / "results")
    p.add_argument("--runs-root", type=Path, default=_ROOT / "results",
                   help="Where to scan for WorkflowManifest evidence (default: results/).")
    p.add_argument("--top-n", type=int, default=10, help="Coords kept per craft list in the JSON.")
    p.add_argument("--output-json", type=Path,
                   default=_ROOT / "site" / "data" / "best-combo-per-craft.json")
    p.add_argument("--output-report", type=Path,
                   default=_ROOT / "docs" / "BEST_COMBO_PER_CRAFT.md")
    a = p.parse_args(argv)

    report = _bc.build_craft_report(
        results_dir=a.results_dir if a.results_dir.exists() else None,
        runs_root=a.runs_root if a.runs_root.exists() else None,
        top_n=a.top_n,
    )
    for path in (a.output_json, a.output_report):
        path.parent.mkdir(parents=True, exist_ok=True)
    a.output_json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    a.output_report.write_text(render_report(report), encoding="utf-8")
    print(
        f"best-combo-per-craft: {report['counts']['processes']} crafts "
        f"({report['counts']['crafts_with_evidence']} with evidence, "
        f"{report['counts']['proven']} proven coords) -> "
        f"{a.output_json}, {a.output_report}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
